image: docker:18.09.2

services:
  - docker:dind

stages:
  - lint
  - build
  - compose

before_script:
  - apk add --no-cache py2-pip nodejs npm git openssh
  - npm install -g yarn
  - pip install --no-cache-dir docker-compose==1.23.2
  - pip install docker-compose

lint:
  stage: lint
  script:
    - yarn install
    - yarn lint

build image(s):
  stage: build
  script:
    - docker-compose build
  artifacts:
    name: "web-dl_website"
    paths:
      - "code/dist/*"

compose services:
  stage: compose
  script:
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true
