include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

image: docker:20.10.6

services:
  - docker:dind

stages:
  - lint
  - build
  - test

before_script:
  - apk update
  - apk add nodejs npm git
  - npm install -g yarn

cache:
  paths:
    - node_modules
    - ~/.bundled
    - ~/.yarn
    - ~/.cache

lint source:
  stage: lint
  script:
    - yarn install
    - yarn lint

build website:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    name: "web-dl_website"
    paths:
      - "dist/*"

docker-build-latest:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - tag=""
    - docker build --platform linux/arm/v7 --pull -t "$CI_REGISTRY_IMAGE${tag}" compose/nginx
    - docker push "$CI_REGISTRY_IMAGE${tag}"

smoke test docker containers:
  stage: test
  before_script:
    - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make rust cargo
    - pip install docker-compose
  script:
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true
