include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

image: docker:20.10.6

services:
  - docker:dind

stages:
  - lint
  - test
  - build

before_script:
  - apk update
  - apk add nodejs npm git
  - npm install -g yarn

cache:
  paths:
    - node_modules
    - ~/.bundled
    - ~/.yarn
    - ~/.cache

lint source:
  stage: lint
  script:
    - yarn install
    - yarn lint

smoke test docker containers:
  stage: test
  before_script:
    - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make rust cargo
    - pip install docker-compose
  script:
    - cp .env.ci .env
    - docker-compose up -d
    - docker ps
  after_script:
    - docker-compose down --remove-orphans || true

build website:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    name: "web-dl_website"
    paths:
      - "dist/*"
