image: docker:20.10.6

services:
  - docker:dind

stages:
  - lint
  - build
  - docker

before_script:
  - apk update
  - apk add --no-cache nodejs npm git
  - npm install -g yarn

cache:
  paths:
    - node_modules/
    - .bundled/
    - .yarn

lint:
  stage: lint
  script:
    - yarn install
    - yarn lint

build website:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    name: "web-dl_website"
    paths:
      - "dist/*"
