version: '2.2'

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
    mem_limit: 20M
    mem_reservation: 10M
    ports:
      - 80:80
    restart: always
