version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
        - SENTRY_DSN=${SENTRY_DSN}
    deploy:
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 10M
    ports:
      - 80:80
    restart: always
