name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_source_code:
    name: Lint source code
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install the node.js application dependencies
      - name: Install dependencies
        run: yarn install

      # Lint the source code
      - name: lint source code
        run: yarn lint
